/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Logica.Animacion;
import javax.swing.JLabel;

/**
 *
 * @author Estudiantes
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    public JLabel getCaballo1() {
        return Caballo1;
    }

    public JLabel getCaballo2() {
        return Caballo2;
    }

    public JLabel getCaballo3() {
        return Caballo3;
    }

    public JLabel getCaballo4() {
        return Caballo4;
    }

    public JLabel getCaballo5() {
        return Caballo5;
    }

    public JLabel getCaballo6() {
        return Caballo6;
    }

    public JLabel getCaballo7() {
        return Caballo7;
    }

    public JLabel getCaballo8() {
        return Caballo8;
    }

    public JLabel getCaballo9() {
        return Caballo9;
    }
    public JLabel getCaballo10() {
        return Caballo10;
    }
    public JLabel getMeta() {
        return Meta;
    }

    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Meta = new javax.swing.JLabel();
        Caballo1 = new javax.swing.JLabel();
        Caballo2 = new javax.swing.JLabel();
        Caballo3 = new javax.swing.JLabel();
        Caballo4 = new javax.swing.JLabel();
        Caballo5 = new javax.swing.JLabel();
        Caballo6 = new javax.swing.JLabel();
        Caballo7 = new javax.swing.JLabel();
        Caballo8 = new javax.swing.JLabel();
        Caballo9 = new javax.swing.JLabel();
        Caballo10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setPreferredSize(new java.awt.Dimension(541, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(505, 640));

        Meta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nahtloses-kariertes-muster-32880425.jpg"))); // NOI18N
        Meta.setText("jLabel1");

        Caballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        Caballo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/horse.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Caballo1)
                    .addComponent(Caballo2)
                    .addComponent(Caballo3)
                    .addComponent(Caballo4)
                    .addComponent(Caballo5)
                    .addComponent(Caballo8)
                    .addComponent(Caballo10)
                    .addComponent(Caballo9)
                    .addComponent(Caballo7)
                    .addComponent(Caballo6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(Meta, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caballo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caballo10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Caballo1.setLocation(0,Caballo1.getLocation().y);
        Caballo2.setLocation(0,Caballo2.getLocation().y);
        Caballo3.setLocation(0,Caballo3.getLocation().y);
        Caballo4.setLocation(0,Caballo4.getLocation().y);
        Caballo5.setLocation(0,Caballo5.getLocation().y);
        Caballo6.setLocation(0,Caballo6.getLocation().y);
        Caballo7.setLocation(0,Caballo7.getLocation().y);
        Caballo8.setLocation(0,Caballo8.getLocation().y);
        Caballo9.setLocation(0,Caballo9.getLocation().y);
        Caballo10.setLocation(0,Caballo10.getLocation().y);
        
        
        Animacion hilo1 = new Animacion(Caballo1, this);
        Animacion hilo2 = new Animacion(Caballo2, this);
        Animacion hilo3 = new Animacion(Caballo3, this);
        Animacion hilo4 = new Animacion(Caballo4, this);
        Animacion hilo5 = new Animacion(Caballo5, this);
        Animacion hilo6 = new Animacion(Caballo6, this);
        Animacion hilo7 = new Animacion(Caballo7, this);
        Animacion hilo8 = new Animacion(Caballo8, this);
        Animacion hilo9 = new Animacion(Caballo9, this);
        Animacion hilo10 = new Animacion(Caballo10, this);
        
        
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();
        hilo5.start();
        hilo6.start();
        hilo7.start();
        hilo8.start();
        hilo9.start();
        hilo10.start();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caballo1;
    private javax.swing.JLabel Caballo10;
    private javax.swing.JLabel Caballo2;
    private javax.swing.JLabel Caballo3;
    private javax.swing.JLabel Caballo4;
    private javax.swing.JLabel Caballo5;
    private javax.swing.JLabel Caballo6;
    private javax.swing.JLabel Caballo7;
    private javax.swing.JLabel Caballo8;
    private javax.swing.JLabel Caballo9;
    private javax.swing.JLabel Meta;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
